### ISSUE TITLE
Brucebox no different than Modded Beepbox

### ISSUE THREAD

**Issue by Theepicosity** [StinkerB06/BruceBox#2]
literally nothing about brucebox is different than modded beepbox except for bad color palette. is this just a problem on my side or is it affecting the whole website? please fix soon

**Comment by StinkerB06** [comment]
Nope. I changed the palette because I like it that way hahaha! The background is aqua turquoise and the font is Comic Sans (or cursive depending on the browser).

**Comment by StinkerB06** [comment]
And it's that way no matter what
